apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  namespace: nexus-gov
spec:
  serviceName: influxdb-svc
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:2.7-alpine
          ports:
            - containerPort: 8086
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: nexus
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              value: nexus2026
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: nexus-gov
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: city_telemetry
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nexus-secrets
                  key: INFLUXDB_TOKEN
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - name: influxdb-data
              mountPath: /var/lib/influxdb2
  volumeClaimTemplates:
    - metadata:
        name: influxdb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  namespace: nexus-gov
spec:
  selector:
    app: influxdb
  ports:
    - port: 8086
      targetPort: 8086
  clusterIP: None
